In [1]:
import pandas as pd
import numpy as np
from scipy import stats

from weighted_kde import *
import tweet_tokenizer

In [2]:
def load_tweets(tweets_attributes_file, tweets_text_file):
    df = pd.read_csv(tweets_attributes_file, index_col=0)
    text = []
    with open(tweets_text_file, 'r') as f:
        for line in f:
            text.append(line)
    df['text'] = text
    return df

In [3]:
# Load tweet data
tweets_attributes_file = 'sandy_tweets_attributes_rev_geocoded_formatted_timestamps.csv'
tweets_text_file = 'sandy_tweets_text_tokenized.txt'

df = load_tweets(tweets_attributes_file, tweets_text_file)
#df = pd.read_csv(open('sandy_tweets_1.csv'), encoding='utf-8', engine='c')
df.head()

,tweet_id,user_id,retweet_count,time_stamp,longitude,latitude,state,county,text
0,260244125050363904,295902181,0,2012-10-22 05:00:09,-74.078101,40.735218,New Jersey,Hudson County,all i wish is to be better than yesterday and ...
1,260244177412042752,85314436,0,2012-10-22 05:00:21,-81.505790,33.460462,South Carolina,Barnwell County,@imSunnyAF yesssss lawd\n
2,260244177105850368,239968255,0,2012-10-22 05:00:21,-77.099999,39.344184,Maryland,Carroll County,"""Waiting for something better , a better you ...."
3,260244156729942016,703352862,0,2012-10-22 05:00:17,-80.907470,39.618102,West Virginia,Tyler County,Cool right ? #plainoldshirt http://t.co/B55dMS...
4,260244145694728192,581488152,0,2012-10-22 05:00:14,-76.579826,39.816450,Pennsylvania,York County,#10PeopleYouTrulyLove My son\n

In [4]:
len(df)

4779087

In [5]:
# Replace missing value in 'county' column by empty string. e.g. Washington D.C.
df['county'] = df['county'].replace(np.nan,'', regex=True)

In [6]:
# Groupby state-conunty pairs and save counts in a new column
# See http://stackoverflow.com/questions/17432944/python-pandas-error-when-doing-groupby-counts

#df['county_tweet_count'] = df.groupby(['state', 'county']).transform('count')
df['county_tweet_count'] = df.groupby(['state', 'county'])['tweet_id'].transform('count')

# Test print
print (len(df[df['state']+df['county'] == 'New JerseyHudson County']))
df.head(6)

52264

,tweet_id,user_id,retweet_count,time_stamp,longitude,latitude,state,county,text,county_tweet_count
0,260244125050363904,295902181,0,2012-10-22 05:00:09,-74.078101,40.735218,New Jersey,Hudson County,all i wish is to be better than yesterday and ...,52264
1,260244177412042752,85314436,0,2012-10-22 05:00:21,-81.505790,33.460462,South Carolina,Barnwell County,@imSunnyAF yesssss lawd\n,1375
2,260244177105850368,239968255,0,2012-10-22 05:00:21,-77.099999,39.344184,Maryland,Carroll County,"""Waiting for something better , a better you ....",7707
3,260244156729942016,703352862,0,2012-10-22 05:00:17,-80.907470,39.618102,West Virginia,Tyler County,Cool right ? #plainoldshirt http://t.co/B55dMS...,175
4,260244145694728192,581488152,0,2012-10-22 05:00:14,-76.579826,39.816450,Pennsylvania,York County,#10PeopleYouTrulyLove My son\n,20191
5,260244141139701760,80608282,1,2012-10-22 05:00:13,-84.472785,39.147755,Ohio,Hamilton County,Mortal kombat ! ! ! ! ! ! @JoeMoDavis #happybi...,51632

In [7]:
# Filter out Sandy related tweets'
#sandy_keywords = ['sandy', 'hurricane', 'storm', 'frankenstorm', 
#                  'power', 'no power', 'blackout',
#                  'gas', 'flooding', 'recovery', 
#                  'weather', 'climate', 'climate change', 'stay safe', 'FEMA']
#sandy_keywords = ['sandy', 'hurricane', 'hurricanesandy', 'frankenstorm', 
#                  'power outage', 'no power', 'blackout', 'no electricity', 'no light',
#                  'no gas', 'flooding',
#                  'climate change', 'fema', 'red cross']
sandy_keywords = ['sandy', 'hurricane', 'hurricanesandy', 'storm', 'frankenstorm']
sandy_keywords = sandy_keywords + ['#'+kw for kw in sandy_keywords]

pattern = ' ' + ' | '.join(sandy_keywords) + ' '
pattern
df_filt = df[df['text'].str.contains(pattern)]

In [8]:
print ('Total number of Sandy related tweets: %d' % len(df_filt))

Total number of Sandy related tweets: 54105

In [9]:
df_filt.head()

,tweet_id,user_id,retweet_count,time_stamp,longitude,latitude,state,county,text,county_tweet_count
2233,260259374579204096,555599291,0,2012-10-22 06:00:44,-77.383514,37.129962,Virginia,City of Petersburg,Tribe storm :)\n,2307
3719,260276715958464512,741091694,0,2012-10-22 07:09:39,-79.147932,37.402037,Virginia,City of Lynchburg,"""Talkin to these kids , making laugh up a stor...",9961
3943,260290515403145216,360388255,0,2012-10-22 08:04:29,-80.015212,40.430596,Pennsylvania,Allegheny County,All I see is a storm that you'll get lost in ....,77561
7303,260350662867562497,529698640,0,2012-10-22 12:03:29,-75.238252,39.953538,Pennsylvania,Delaware County,http://t.co/BhhL8usJ praise GOD n the storm . ...,53618
10147,260366743153823745,39651540,0,2012-10-22 13:07:23,-75.586010,39.945970,Pennsylvania,Chester County,@BigJoeBastardi what are water temps off e coa...,20863

## Google map plots

In [10]:
import gmaps
import gmaps.datasets

gmaps.configure(api_key="AIzaSyAWVuwTc9I0KC6jskl6_yZwOzhhG8J3MsA") # Your Google API key

In [11]:
data = list(df_filt[['latitude', 'longitude']].apply(tuple, axis=1))
data[:3]

[(37.129962140000004, -77.383514340000005),
 (37.402037, -79.147931900000003),
 (40.430596350000002, -80.015212329999997)]

In [24]:
from matplotlib import cm

rgba = []
for i in xrange(255):
    rgba_val = list(cm.jet(i))
    rgba_val = [int(v*255) for v in rgba_val]
    rgba_val[3] = 0.99*(1-i/256.0)
    rgba.append(tuple(rgba_val))
    
rgba

[(0, 0, 127, 0.99),
 (0, 0, 132, 0.9861328125),
 (0, 0, 136, 0.982265625),
 (0, 0, 141, 0.9783984375),
 (0, 0, 145, 0.97453125),
 (0, 0, 150, 0.9706640625),
 (0, 0, 154, 0.966796875),
 (0, 0, 159, 0.9629296875),
 (0, 0, 163, 0.9590625),
 (0, 0, 168, 0.9551953125),
 (0, 0, 172, 0.951328125),
 (0, 0, 177, 0.9474609375),
 (0, 0, 182, 0.94359375),
 (0, 0, 186, 0.9397265625),
 (0, 0, 191, 0.9358593749999999),
 (0, 0, 195, 0.9319921875),
 (0, 0, 200, 0.928125),
 (0, 0, 204, 0.9242578124999999),
 (0, 0, 209, 0.920390625),
 (0, 0, 213, 0.9165234375),
 (0, 0, 218, 0.91265625),
 (0, 0, 222, 0.9087890625),
 (0, 0, 227, 0.904921875),
 (0, 0, 232, 0.9010546875),
 (0, 0, 236, 0.8971875),
 (0, 0, 241, 0.8933203125),
 (0, 0, 245, 0.889453125),
 (0, 0, 250, 0.8855859375),
 (0, 0, 254, 0.88171875),
 (0, 0, 255, 0.8778515625),
 (0, 0, 255, 0.873984375),
 (0, 0, 255, 0.8701171875),
 (0, 0, 255, 0.86625),
 (0, 4, 255, 0.8623828125),
 (0, 8, 255, 0.858515625),
 (0, 12, 255, 0.8546484375),
 (0, 16, 255, 0.85078125),
 (0, 20, 255, 0.8469140625),
 (0, 24, 255, 0.843046875),
 (0, 28, 255, 0.8391796874999999),
 (0, 32, 255, 0.8353125),
 (0, 36, 255, 0.8314453125),
 (0, 40, 255, 0.8275781249999999),
 (0, 44, 255, 0.8237109375),
 (0, 48, 255, 0.81984375),
 (0, 52, 255, 0.8159765625),
 (0, 56, 255, 0.812109375),
 (0, 60, 255, 0.8082421875),
 (0, 64, 255, 0.804375),
 (0, 68, 255, 0.8005078125),
 (0, 72, 255, 0.796640625),
 (0, 76, 255, 0.7927734375),
 (0, 80, 255, 0.78890625),
 (0, 84, 255, 0.7850390625),
 (0, 88, 255, 0.781171875),
 (0, 92, 255, 0.7773046875),
 (0, 96, 255, 0.7734375),
 (0, 100, 255, 0.7695703125),
 (0, 104, 255, 0.765703125),
 (0, 108, 255, 0.7618359375),
 (0, 112, 255, 0.75796875),
 (0, 116, 255, 0.7541015625),
 (0, 120, 255, 0.750234375),
 (0, 124, 255, 0.7463671875),
 (0, 128, 255, 0.7424999999999999),
 (0, 132, 255, 0.7386328125),
 (0, 136, 255, 0.734765625),
 (0, 140, 255, 0.7308984374999999),
 (0, 144, 255, 0.72703125),
 (0, 148, 255, 0.7231640625),
 (0, 152, 255, 0.719296875),
 (0, 156, 255, 0.7154296875),
 (0, 160, 255, 0.7115625),
 (0, 164, 255, 0.7076953125),
 (0, 168, 255, 0.703828125),
 (0, 172, 255, 0.6999609375),
 (0, 176, 255, 0.69609375),
 (0, 180, 255, 0.6922265625),
 (0, 184, 255, 0.688359375),
 (0, 188, 255, 0.6844921875),
 (0, 192, 255, 0.680625),
 (0, 196, 255, 0.6767578125),
 (0, 200, 255, 0.672890625),
 (0, 204, 255, 0.6690234375),
 (0, 208, 255, 0.66515625),
 (0, 212, 255, 0.6612890625),
 (0, 216, 255, 0.657421875),
 (0, 220, 254, 0.6535546875),
 (0, 224, 250, 0.6496875),
 (0, 228, 247, 0.6458203125),
 (2, 232, 244, 0.641953125),
 (5, 236, 241, 0.6380859375),
 (8, 240, 237, 0.6342187499999999),
 (12, 244, 234, 0.6303515625),
 (15, 248, 231, 0.626484375),
 (18, 252, 228, 0.6226171875),
 (21, 255, 225, 0.61875),
 (24, 255, 221, 0.6148828125),
 (28, 255, 218, 0.611015625),
 (31, 255, 215, 0.6071484375),
 (34, 255, 212, 0.60328125),
 (37, 255, 208, 0.5994140625),
 (41, 255, 205, 0.595546875),
 (44, 255, 202, 0.5916796875),
 (47, 255, 199, 0.5878125),
 (50, 255, 195, 0.5839453125),
 (54, 255, 192, 0.580078125),
 (57, 255, 189, 0.5762109375),
 (60, 255, 186, 0.57234375),
 (63, 255, 183, 0.5684765625),
 (66, 255, 179, 0.564609375),
 (70, 255, 176, 0.5607421875),
 (73, 255, 173, 0.556875),
 (76, 255, 170, 0.5530078125),
 (79, 255, 166, 0.549140625),
 (83, 255, 163, 0.5452734375),
 (86, 255, 160, 0.54140625),
 (89, 255, 157, 0.5375390624999999),
 (92, 255, 154, 0.533671875),
 (95, 255, 150, 0.5298046875),
 (99, 255, 147, 0.5259375),
 (102, 255, 144, 0.5220703125),
 (105, 255, 141, 0.518203125),
 (108, 255, 137, 0.5143359375),
 (112, 255, 134, 0.51046875),
 (115, 255, 131, 0.5066015625),
 (118, 255, 128, 0.502734375),
 (121, 255, 125, 0.4988671875),
 (124, 255, 121, 0.495),
 (128, 255, 118, 0.4911328125),
 (131, 255, 115, 0.487265625),
 (134, 255, 112, 0.4833984375),
 (137, 255, 108, 0.47953125),
 (141, 255, 105, 0.4756640625),
 (144, 255, 102, 0.471796875),
 (147, 255, 99, 0.46792968749999997),
 (150, 255, 95, 0.4640625),
 (154, 255, 92, 0.4601953125),
 (157, 255, 89, 0.456328125),
 (160, 255, 86, 0.4524609375),
 (163, 255, 83, 0.44859375),
 (166, 255, 79, 0.4447265625),
 (170, 255, 76, 0.440859375),
 (173, 255, 73, 0.4369921875),
 (176, 255, 70, 0.433125),
 (179, 255, 66, 0.4292578125),
 (183, 255, 63, 0.425390625),
 (186, 255, 60, 0.4215234375),
 (189, 255, 57, 0.41765625),
 (192, 255, 54, 0.41378906249999997),
 (195, 255, 50, 0.409921875),
 (199, 255, 47, 0.4060546875),
 (202, 255, 44, 0.4021875),
 (205, 255, 41, 0.3983203125),
 (208, 255, 37, 0.394453125),
 (212, 255, 34, 0.3905859375),
 (215, 255, 31, 0.38671875),
 (218, 255, 28, 0.3828515625),
 (221, 255, 24, 0.378984375),
 (224, 255, 21, 0.3751171875),
 (228, 255, 18, 0.37124999999999997),
 (231, 255, 15, 0.3673828125),
 (234, 255, 12, 0.363515625),
 (237, 255, 8, 0.3596484375),
 (241, 252, 5, 0.35578125),
 (244, 248, 2, 0.3519140625),
 (247, 244, 0, 0.348046875),
 (250, 240, 0, 0.3441796875),
 (254, 237, 0, 0.3403125),
 (255, 233, 0, 0.3364453125),
 (255, 229, 0, 0.332578125),
 (255, 226, 0, 0.3287109375),
 (255, 222, 0, 0.32484375),
 (255, 218, 0, 0.3209765625),
 (255, 215, 0, 0.31710937499999997),
 (255, 211, 0, 0.3132421875),
 (255, 207, 0, 0.309375),
 (255, 203, 0, 0.3055078125),
 (255, 200, 0, 0.301640625),
 (255, 196, 0, 0.2977734375),
 (255, 192, 0, 0.29390625),
 (255, 189, 0, 0.2900390625),
 (255, 185, 0, 0.286171875),
 (255, 181, 0, 0.2823046875),
 (255, 177, 0, 0.2784375),
 (255, 174, 0, 0.2745703125),
 (255, 170, 0, 0.270703125),
 (255, 166, 0, 0.2668359375),
 (255, 163, 0, 0.26296875),
 (255, 159, 0, 0.2591015625),
 (255, 155, 0, 0.255234375),
 (255, 152, 0, 0.2513671875),
 (255, 148, 0, 0.2475),
 (255, 144, 0, 0.2436328125),
 (255, 140, 0, 0.239765625),
 (255, 137, 0, 0.2358984375),
 (255, 133, 0, 0.23203125),
 (255, 129, 0, 0.2281640625),
 (255, 126, 0, 0.224296875),
 (255, 122, 0, 0.2204296875),
 (255, 118, 0, 0.2165625),
 (255, 115, 0, 0.2126953125),
 (255, 111, 0, 0.208828125),
 (255, 107, 0, 0.2049609375),
 (255, 103, 0, 0.20109375),
 (255, 100, 0, 0.1972265625),
 (255, 96, 0, 0.193359375),
 (255, 92, 0, 0.1894921875),
 (255, 89, 0, 0.18562499999999998),
 (255, 85, 0, 0.1817578125),
 (255, 81, 0, 0.177890625),
 (255, 77, 0, 0.1740234375),
 (255, 74, 0, 0.17015625),
 (255, 70, 0, 0.1662890625),
 (255, 66, 0, 0.162421875),
 (255, 63, 0, 0.15855468749999999),
 (255, 59, 0, 0.1546875),
 (255, 55, 0, 0.1508203125),
 (255, 52, 0, 0.146953125),
 (255, 48, 0, 0.1430859375),
 (255, 44, 0, 0.13921875),
 (255, 40, 0, 0.1353515625),
 (255, 37, 0, 0.131484375),
 (255, 33, 0, 0.1276171875),
 (255, 29, 0, 0.12375),
 (255, 26, 0, 0.1198828125),
 (255, 22, 0, 0.116015625),
 (254, 18, 0, 0.1121484375),
 (250, 15, 0, 0.10828125),
 (245, 11, 0, 0.1044140625),
 (241, 7, 0, 0.100546875),
 (236, 3, 0, 0.0966796875),
 (232, 0, 0, 0.09281249999999999),
 (227, 0, 0, 0.0889453125),
 (222, 0, 0, 0.085078125),
 (218, 0, 0, 0.0812109375),
 (213, 0, 0, 0.07734375),
 (209, 0, 0, 0.0734765625),
 (204, 0, 0, 0.069609375),
 (200, 0, 0, 0.0657421875),
 (195, 0, 0, 0.061875),
 (191, 0, 0, 0.0580078125),
 (186, 0, 0, 0.054140625),
 (182, 0, 0, 0.0502734375),
 (177, 0, 0, 0.046406249999999996),
 (172, 0, 0, 0.0425390625),
 (168, 0, 0, 0.038671875),
 (163, 0, 0, 0.0348046875),
 (159, 0, 0, 0.0309375),
 (154, 0, 0, 0.0270703125),
 (150, 0, 0, 0.023203124999999998),
 (145, 0, 0, 0.0193359375),
 (141, 0, 0, 0.01546875),
 (136, 0, 0, 0.011601562499999999),
 (132, 0, 0, 0.007734375)]

In [25]:
# Min and max lat-lon for whole dataset
lon_min, lon_max = df['longitude'].values.min(), df['longitude'].values.max()
lat_min, lat_max = df['latitude'].values.min(), df['latitude'].values.max()

# Map Sandy related Twitter activity on Google Maps
# Define our longitude and latitude points
# Here we use only power outage related data
filtered_lon_vals, filtered_lat_vals = df_filt['longitude'].values, df_filt['latitude'].values

weights = 1.0/df_filt['county_tweet_count'].values

data = list(df_filt[['latitude', 'longitude']].apply(tuple, axis=1))
m = gmaps.Map()
heatmap_layer = gmaps.Heatmap(data=data)

#heatmap_layer.max_intensity = 10
heatmap_layer.point_radius = 20

m.add_layer(heatmap_layer)
#heatmap_layer.gradient = [
#    (255, 255, 255, 0.01),
#    (255, 165, 0, 0.4),
#    (255, 69, 0, 0.6),
#    (255, 0, 0, 0.8)
#]
heatmap_layer.gradient = rgba
m

In [33]:
print (heatmap_layer.max_intensity)

None

In [31]:
# Min and max lat-lon for whole dataset
lon_min, lon_max = df['longitude'].values.min(), df['longitude'].values.max()
lat_min, lat_max = df['latitude'].values.min(), df['latitude'].values.max()

# Map Sandy related Twitter activity on Google Maps
# Define our longitude and latitude points
# Here we use only power outage related data
filtered_lats, filtered_lons = df_filt['latitude'].values, df_filt['longitude'].values

weights = 1.0/df_filt['county_tweet_count'].values
weights *= 100/max(weights)

df_temp = pd.DataFrame({'lat': filtered_lats, 'lon': filtered_lons, 'wt': weights})
df_temp.head()

data = list(df_temp.apply(tuple, axis=1))
m_weighted = gmaps.Map()
heatmap_layer = gmaps.WeightedHeatmap(data=data)
#heatmap_layer.max_intensity = 10
heatmap_layer.point_radius = 20
m_weighted.add_layer(heatmap_layer)
m_weighted